### ISSUE TITLE
Output device ignored if default system device is different

### ISSUE THREAD

**Issue by nopap** [cern-phone-apps/desktop-phone-app#137]
**Describe the bug**
CERNPhone is configured to use  Jabra headset as input/output device. 
Windows System default device is set to speakers.
When taking a call, i get no sound in the Jabra speakers until i do either: 
   - open CERNPhone settings and check output (no need to change, just check and sound comes back)
   - change the system output device to Jabra

**Expected behavior**
CERNPhone should keep the selected output device.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 18985
 - App Version 0.5.5

**Comment by lorys** [comment]
***Windows issue***

This issue is related to devices able to do ***headset AND headphones a the same time*** (mostly bluetooth). So we have to tell windows the purpose of this device.

If you try to do these steps it may work : 
- ***Right click*** on the speaker icon in windows taskbar and choose "***Sounds***"
- A window opens, go to the "***Playback***" section
- Right Click on "Headphones" (if you have it) and disable it.
- Go to cern phone application and open settings, and then select the device that you want.

# Wrong Config
![wrong_config](https://user-images.githubusercontent.com/31002428/65866560-4cc26d80-e375-11e9-9ac0-4898d5d6a1d8.png)
# Right Config
![right_config](https://user-images.githubusercontent.com/31002428/65866630-711e4a00-e375-11e9-920f-1f6df7195044.png)

**Comment by nopap** [comment]
Well we can't ask people to disable all output devices but the phone headset...

**Comment by lorys** [comment]
This bug is not stable, we have to figure out a way to reproduce it.

I tested the Jabra headset and I didn't managed to reproduce the bug.
I tested :
- open app and directly make a call : ***worked***
- check settings then make a call : ***worked***
- open settings while I was on a call : ***worked***
- open settings and select one by one every output/input (5 devices in/out) while I was on a call : ***worked***
- open settings and select one by one every output/input (5 devices in/out) AND changed windows default output device while I was on a call : ***worked***

The only case where it hasn't worked is this one : 
![weird](https://user-images.githubusercontent.com/31002428/65949595-cbcea900-e43c-11e9-9e4d-2a336ed27957.png)
Windows was receiving sounds from the webapp but I couldn't hear anything. Unfortunately I am not able to reproduce this bug. It worked when I changed the default device in windows settings. The weird part is when I put back the same bugged config it worked.
